### ISSUE TITLE
Url https://opendata.arcgis.com/datasets/3b374840ce1b4160b85b8146b610cd0c_0.geojson is 404

### ISSUE THREAD

**Issue by robmarkcole** [espayne/Choropleth-Mapping-UK-python-#1]
Could you advise on the readme the appropriate search term or url to return this file? Thanks!

**Comment by espayne** [comment]
Ah I see, I think they have removed this link, you should be able to use these instead:

https://geoportal.statistics.gov.uk/datasets/local-authority-districts-may-2021-uk-bgc/explore?location=54.078851%2C-1.429765%2C6.34

https://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2020-uk-bfc/explore?location=54.450649%2C-2.854949%2C6.09

**Comment by robmarkcole** [comment]
Many thanks!
